[build]
	command = "npm run build"
	publish = "build"
	functions = "functions-build"

[functions]
	directory = "netlify/functions"
	node_bundler = "nft"
	external_node_modules = ["@datastax/astra-db-ts"]

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200