[build]
	command = "CI=false npm run build"
	publish = "build"

[functions]
	directory = "netlify/functions"
	# Tell Netlify NOT to bundle this module, make it available directly
	external_node_modules = ["@datastax/astra-db-ts"]

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200